DROP TABLE IF EXISTS `logs`;
CREATE TABLE `logs` (
    date    DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    browser VARCHAR(500) NOT NULL DEFAULT '',
    is_bot  TINYINT(1)   NOT NULL DEFAULT 0
);

ALTER TABLE `logs` MODIFY COLUMN `date` DATETIME(3) NOT NULL;
